version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vue3"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/vue2"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
    groups:
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/example/vue3"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/example/vue2"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    labels:
      - "chore"
    groups:
      all:
        patterns:
          - "*"
